harness int[n] studentDeriv(int n, int[n] in){
    int[n] deriv = {};
    int zero = 0;
    if(n == 1){
        return {0};
    }
    for(int i=0; i<n; ++i){
        if(in[i] == 0 || ??){
            zero += 1;
        }else{
            deriv[i] = in[i]*i;
        }
    } 
    return deriv[1:n-1];
}

int[n] correctDeriv(int n, int[n] in){
    int[n] result = {};
    for(int i=0; i<n; ++i){
        result[i] = in[i]*i;
    }
    if(n == 1){
        return result;
    }else{
        return result[1:n-1];
    }
}

void driver(int n, int[n] in){
    assert correctDeriv(n, in) == correctDeriv(n, in);
}
