harness void studentDeriv(int n, int[n] in){
    int[n] deriv;
    deriv[0] = 0;
    int zero = 0;
    if(n == 1){
        assert deriv[??:??] == correctDeriv(n, in);
    }
    for(int e=0; e<n; ++e){
        if(in[e] == 0){
            zero += 1;
        }else{
            deriv[e] = in[e]*e;
        }
    }
    
    assert deriv[??:??] == correctDeriv(n, in);
}

int[n] correctDeriv(int n, int[n] in){
    int[n] result = in;
    for(int i=0; i<n; ++i){
        result[i] = in[i]*i;
    }
    if(n == 1){
        return result;
    }else{
        return result[1:n-1];
    }
}
